### ISSUE TITLE
Ability to generate multiple pages

### ISSUE THREAD

**Issue by ZachTRice** [bootpack/bootpack#62]
The webpack configuration currently is tailored to creating a single page. Allowing users to set up multiple pages right away, or at the very least, provide documentation on how to add multiple pages, would be useful.

**Comment by aalekseenkov** [comment]
npm install html-webpack-plugin raw-loader --save-dev
===
...
const HtmlWebpackPlugin = require('html-webpack-plugin');
const fs = require('fs')

function generateHtmlPlugins(templateDir) {
  const templateFiles = fs.readdirSync(path.resolve(__dirname, templateDir));
  return templateFiles.map(item => {
    const parts = item.split('.');
    const name = parts[0];
    const extension = parts[1];
    return new HtmlWebpackPlugin({
      filename: `${name}.html`,
      template: path.resolve(__dirname, `${templateDir}/${name}.${extension}`),
      inject: false,
    })
  })
}

const htmlPlugins = generateHtmlPlugins('./src/html/views')

module.exports = {
  module: {
      ...
      {
        test: /\.html$/,
        include: path.resolve(__dirname, 'src/html/includes'),
        use: ['raw-loader']
      },
    ]
  },
  plugins: [
    ...
  ].concat(htmlPlugins)
};

**Comment by ZachTRice** [comment]
This feature has now been merged. Thanks @aalekseenkov for the code snippet.
